WebApplication1/Models/Carro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Carro
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "A Placa é Obrigatório!")]
        public string Placa { get; set; }

        [Required(ErrorMessage = "O Modelo é Obrigatório!")]
        public string Modelo { get; set; }

        [Required(ErrorMessage = "O Ano de Fabricação é obrigatório.")]

        [DataType(DataType.Date)]

        [Display(Name = "Ano de Fabricação")]
        public DateTime Ano { get; set; }


        
        [Required(ErrorMessage = "A Cor é Obrigatória!")]
        public string Cor { get; set; }

        // Método para retornar o ano do carro
        public string GetDataCarro()
        {
            return Ano.ToString("yyyy");
        }

        // Método para gerar a lista de carros na sessão, caso ainda não exista
        public static void GerarListaCarro(HttpSessionStateBase session)
        {
            if (session["ListaCarro"] == null)
            {
                session["ListaCarro"] = new List<Carro>();  
            }
        }

 
        public static Carro ProcurarCarro(HttpSessionStateBase session, int id)
        {
            if (session["ListaCarro"] != null)
            {
                return (session["ListaCarro"] as List<Carro>)?.ElementAtOrDefault(id); 
            }

            return null;
        }


        public void ExcluirCarro(HttpSessionStateBase session)
        {
            if (session["ListaCarro"] != null)
            {
                var lista = session["ListaCarro"] as List<Carro>;
                lista?.Remove(this); 
            }
        }


        public void AdicionarCarro(HttpSessionStateBase session)
        {
            var lista = session["ListaCarro"] as List<Carro>;

            if (lista != null)
            {
                this.Id = lista.Any() ? lista.Max(c => c.Id) + 1 : 0; 
                lista.Add(this); 
            }
        }


        public void EditarCarro(HttpSessionStateBase session, int id)
        {
            var lista = session["ListaCarro"] as List<Carro>;
            if (lista != null)
            {
                var carro = lista.ElementAtOrDefault(id);
                if (carro != null)
                {
                    carro.Placa = this.Placa;
                    carro.Ano = this.Ano;
                    carro.Modelo = this.Modelo;
                    carro.Cor = this.Cor;
                }
            }
        }
    }
}

WebApplication1/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CarroController : Controller
    {
        // GET: Carro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            Carro.GerarListaCarro(Session);
            return View(Session["ListaCarro"] as List<Carro>);
        }

        public ActionResult Exibir(int id)
        {
            return View((Session["ListaCarro"] as List<Carro>)?.ElementAt(id));
        }


        [HttpPost]
        public ActionResult DeleteAjax(int id)
        {
            try
            {
                var carros = Session["ListaCarro"] as List<Carro>;
                var carro = carros?.FirstOrDefault(c => c.Id == id);

                if (carro == null)
                    return Json(new { sucesso = false, mensagem = "Carro não encontrado." });

                carros.Remove(carro);
                Session["ListaCarro"] = carros;

                return Json(new { sucesso = true, mensagem = "Carro excluído com sucesso." });
            }
            catch (Exception ex)
            {
                return Json(new { sucesso = false, mensagem = "Erro ao excluir carro: " + ex.Message });
            }
        }


        public ActionResult Edit(int id)
        {
            var carro = (Session["ListaCarro"] as List<Carro>)?.ElementAtOrDefault(id);
            if (carro != null)
            {
                return View(carro);
            }


            return RedirectToAction("Listar");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Carro carro)
        {
            var listaCarro = Session["ListaCarro"] as List<Carro>;
            if (listaCarro == null)
            {
                return RedirectToAction("Listar");
            }

            var carroExistente = listaCarro.ElementAtOrDefault(id);
            if (carroExistente == null)
            {
                return RedirectToAction("Listar");
            }

            carroExistente.Placa = carro.Placa;
            carroExistente.Ano = carro.Ano;
            carroExistente.Cor = carro.Cor;

            Session["ListaCarro"] = listaCarro;

            return RedirectToAction("Listar");
        }


        public ActionResult Create()
        {
            return View(new Carro());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Carro carro)
        {
            if (ModelState.IsValid)
            {
                carro.AdicionarCarro(Session);
                return RedirectToAction("Listar");
            }

  
            return View(carro);
        }
    }
}

WebApplication1/Controllers/ExcelController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ExcelController : Controller
    {
        [Obsolete]
        public ActionResult DownloadExcel(string tema)
        {
            object listaDados = null;

            switch (tema.ToLower())
            {
                case "aluno":
                    listaDados = Session["ListaAluno"] as List<Aluno>;
                    break;
                case "carro":
                    listaDados = Session["ListaCarro"] as List<Carro>;
                    break;
                case "evento":
                    listaDados = Session["ListaEvento"] as List<Evento>;
                    break;
                case "celular":
                    listaDados = Session["ListaCelular"] as List<Celular>;
                    break;
                default:
                    return HttpNotFound("Tema não encontrado!");
            }

            if (listaDados == null || (listaDados is IEnumerable<object> lista && !lista.Any()))
            {
                return HttpNotFound("Não há dados cadastrados para o tema selecionado!");
            }

            ExcelPackage.License.SetNonCommercialOrganization("Terrier Corp.");

            using (var pacote = new ExcelPackage())
            {
                var planilha = pacote.Workbook.Worksheets.Add("Relatório");

                // Cabeçalhos
                int coluna = 1;
                int linha = 1;

                if (tema.ToLower() == "aluno")
                {
                    var alunos = listaDados as List<Aluno>;
                    planilha.Cells[linha, 1].Value = "Nome";
                    planilha.Cells[linha, 2].Value = "Email";
                    planilha.Cells[linha, 3].Value = "RA";
                    planilha.Cells[linha, 4].Value = "Nascimento";
                    linha++;

                    foreach (var aluno in alunos)
                    {
                        planilha.Cells[linha, 1].Value = aluno.Nome;
                        planilha.Cells[linha, 2].Value = aluno.Email;
                        planilha.Cells[linha, 3].Value = aluno.RA;
                        planilha.Cells[linha, 4].Value = aluno.Nascimento.ToShortDateString();
                        linha++;
                    }
                }
                else if (tema.ToLower() == "carro")
                {
                    var carros = listaDados as List<Carro>;
                    planilha.Cells[linha, 1].Value = "Placa";
                    planilha.Cells[linha, 2].Value = "Ano";
                    planilha.Cells[linha, 3].Value = "Cor";
                    linha++;

                    foreach (var carro in carros)
                    {
                        planilha.Cells[linha, 1].Value = carro.Placa;
                        planilha.Cells[linha, 2].Value = carro.Ano.ToString("yyyy");
                        planilha.Cells[linha, 3].Value = carro.Cor;
                        linha++;
                    }
                }
                else if (tema.ToLower() == "evento")
                {
                    var eventos = listaDados as List<Evento>;
                    planilha.Cells[linha, 1].Value = "Nome";
                    planilha.Cells[linha, 2].Value = "Banda";
                    planilha.Cells[linha, 3].Value = "Local";
                    planilha.Cells[linha, 4].Value = "Data";
                    linha++;

                    foreach (var evento in eventos)
                    {
                        planilha.Cells[linha, 1].Value = evento.Nome;
                        planilha.Cells[linha, 2].Value = evento.Banda;
                        planilha.Cells[linha, 3].Value = evento.Local;
                        planilha.Cells[linha, 4].Value = evento.Data.ToShortDateString();
                        linha++;
                    }
                }
                else if (tema.ToLower() == "celular")
                {
                    var celulares = listaDados as List<Celular>;
                    planilha.Cells[linha, 1].Value = "Número";
                    planilha.Cells[linha, 2].Value = "Marca";
                    planilha.Cells[linha, 3].Value = "Novo";
                    planilha.Cells[linha, 4].Value = "Fabricação";
                    linha++;

                    foreach (var celular in celulares)
                    {
                        planilha.Cells[linha, 1].Value = celular.Numero;
                        planilha.Cells[linha, 2].Value = celular.Marca;
                        planilha.Cells[linha, 3].Value = celular.Novo ? "Sim" : "Não";
                        planilha.Cells[linha, 4].Value = celular.Fabrica.ToShortDateString();
                        linha++;
                    }
                }

                // Estilo para cabeçalhos
                using (var range = planilha.Cells[1, 1, 1, coluna + 3])
                {
                    range.Style.Font.Bold = true;
                    range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                    range.Style.Fill.BackgroundColor.SetColor(Color.LightGray);
                }

                planilha.Cells.AutoFitColumns();

                string nomeArquivo = $"Relatorio_{tema}.xlsx";
                return File(pacote.GetAsByteArray(),
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            nomeArquivo);
            }
        }
    }
}

WebApplication1/Controllers/PDfController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PdfController : Controller
    {
        public ActionResult DownloadPdf(string tema)
        { 
            object listaDados = null;

            switch (tema.ToLower())
            {
                case "aluno":
                    listaDados = Session["ListaAluno"] as List<Aluno>;
                    break;
                case "carro":
                    listaDados = Session["ListaCarro"] as List<Carro>;
                    break;
                case "evento":
                    listaDados = Session["ListaEvento"] as List<Evento>;
                    break;
                case "celular":
                    listaDados = Session["ListaCelular"] as List<Celular>;
                    break;
                default:
                    return HttpNotFound("Tema não encontrado!");
            }

            if (listaDados == null || (listaDados is IEnumerable<object> lista && !lista.Any()))
            {
                return HttpNotFound("Não há dados cadastrados para o tema selecionado!");
            }

            using (MemoryStream memoryStream = new MemoryStream())
            {
                Document document = new Document();
                PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);
                document.Open();

                document.Add(new Paragraph($"Relatório de {tema}"));
                document.Add(new Paragraph(" "));

                if (tema.ToLower() == "aluno")
                {
                    var alunos = listaDados as List<Aluno>;
                    foreach (var aluno in alunos)
                    {
                        document.Add(new Paragraph($"Nome: {aluno.Nome}"));
                        document.Add(new Paragraph($"RA: {aluno.RA}"));
                        document.Add(new Paragraph($"Nascimento: {aluno.Nascimento.ToShortDateString()}"));
                        document.Add(new Paragraph("--------------"));
                    }
                }
                else if (tema.ToLower() == "carro")
                {
                    var carros = listaDados as List<Carro>;
                    foreach (var carro in carros)
                    {
                        document.Add(new Paragraph($"Placa: {carro.Placa}"));
                        document.Add(new Paragraph($"Ano: {carro.Ano.ToString("yyyy")}"));
                        document.Add(new Paragraph($"Cor: {carro.Cor}"));
                        document.Add(new Paragraph("--------------"));
                    }
                }
                else if (tema.ToLower() == "evento")
                {
                    var eventos = listaDados as List<Evento>;
                    foreach (var evento in eventos)
                    {
                        document.Add(new Paragraph($"Nome: {evento.Nome}"));
                        document.Add(new Paragraph($"Banda: {evento.Banda}"));
                        document.Add(new Paragraph($"Local: {evento.Local}"));
                        document.Add(new Paragraph($"Data: {evento.Data.ToShortDateString()}"));
                        document.Add(new Paragraph("--------------"));
                    }
                }
                else if (tema.ToLower() == "celular")
                {
                    var celulares = listaDados as List<Celular>;
                    foreach (var celular in celulares)
                    {
                        document.Add(new Paragraph($"Número: {celular.Numero}"));
                        document.Add(new Paragraph($"Marca: {celular.Marca}"));
                        document.Add(new Paragraph($"Novo: {(celular.Novo ? "Sim" : "Não")}"));
                        document.Add(new Paragraph($"Fabricação: {celular.Fabrica.ToShortDateString()}"));
                        document.Add(new Paragraph("--------------"));
                    }
                }

                document.Close();
                writer.Close();

                byte[] fileBytes = memoryStream.ToArray();
                return File(fileBytes, "application/pdf", $"Relatorio_{tema}.pdf");
            }
        }
    }
}

WebApplication1/Views/Carro/Create.cshtml
@model WebApplication1.Models.Carro

@{
    ViewBag.Title = "Cadastro de Carro";
}

<h2 class="text-center mb-4">Cadastrar Carro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="card p-4 shadow-sm">
            <h4 class="text-primary">Preencha os Detalhes do Carro</h4>
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <!-- Placa -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Modelo -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Ano -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Cor -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Cor, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Botão Criar -->
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-outline-success btn-lg">Cadastrar</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="mt-4 text-center">
    @Html.ActionLink("Voltar", "Listar", null, new { @class = "btn btn-outline-primary" })
</div>

WebApplication1/Views/Carro/Delete.cshtml
@model WebApplication1.Models.Carro

@{
    ViewBag.Title = "Deletar";
}

<h2>Excluir: </h2>

<h3>Você tem certeza que deseja excluir este registro?</h3>
<div>
    <h4>Carro: @Html.DisplayFor(model => model.Placa)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Model.GetDataCarro()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="mt-2 form-actions no-color">
            <input type="submit" value="Delete" class="btn-block btn btn-outline-danger" /> |
            <button class="btn-block btn btn-outline-primary">@Html.ActionLink("Voltar", "Listar")</button>
        </div>
    }
</div>

WebApplication1/Views/Carro/Edit.cshtml
@model WebApplication1.Models.Carro

@{
    ViewBag.Title = "Editar Carro";
}

<h2 class="text-center mb-4">Editar Carro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="card p-4 shadow-sm">
            <h4 class="text-primary">Detalhes do Carro</h4>
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <!-- Placa -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Modelo -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Ano -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Cor -->
            <div class="form-group row">
                @Html.LabelFor(model => model.Cor, htmlAttributes: new { @class = "col-md-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </div>
            </div>

            <!-- Botão Salvar -->
            <div class="form-group row">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-outline-success btn-lg">Salvar</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="mt-4 text-center">
    @Html.ActionLink("Voltar", "Listar", null, new { @class = "btn btn-outline-primary" })
</div>

WebApplication1/Views/Carro/Exibir.cshtml
@model WebApplication1.Models.Carro

@{
    ViewBag.Title = "Exibir";
}

<h2>Exibir: </h2>

<div>
    <h4>Carro: @Html.DisplayFor(model => model.Placa)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Model.GetDataCarro()
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cor)
        </dd>

    </dl>
</div>
<div class="mt-2">
    <button class="btn btn-outline-primary">
        @Html.ActionLink("Editar", "Edit", new { /*id = Model.PrimaryKey */ }) 
    </button>
    <button class="btn btn-outline-secondary">
        @Html.ActionLink("Voltar", "Listar")
    </button>
</div>

WebApplication1/Views/Carro/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Carros</h2>

WebApplication1/Views/Carro/Listar.cshtml
@model IEnumerable<WebApplication1.Models.Carro>

@{
    ViewBag.Title = "Lista de Carros";
}

<h2 class="mb-4">Lista de Carros</h2>

<div class="mb-3">
    @Html.ActionLink("Cadastrar", "Create", null, new { @class = "btn btn-outline-primary" })
    <a href="@Url.Action("DownloadPdf", "Pdf", new { tema = "carro" })" class="btn btn-outline-danger">📄 Exportar PDF</a>
    <a href="@Url.Action("DownloadExcel", "Excel", new { tema = "carro" })" class="btn btn-outline-success">📊 Exportar Excel</a>
</div>

<table id="tabelaCarros" class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Placa)</th>
            <th>@Html.DisplayNameFor(model => model.Ano)</th>
            <th>@Html.DisplayNameFor(model => model.Ano)</th>
            <th>@Html.DisplayNameFor(model => model.Modelo)</th>
            <th style="width: 150px;">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Placa)</td>
                <td>@item.GetDataCarro()</td>
                <td>@Html.DisplayFor(m => item.Cor)</td>
                <td>@Html.DisplayFor(m => item.Modelo)</td>
                <td>
                    @Html.ActionLink("✏️ Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-outline-info btn-sm" })
                    <button class="btn btn-outline-danger btn-sm" onclick="confirmarExclusao(@item.Id, '@item.Placa')">🗑 Excluir</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal de Exclusão -->
<div class="modal fade" id="modalExcluir" tabindex="-1" role="dialog" aria-labelledby="modalExcluirLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="modalExcluirLabel">Confirmar Exclusão</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Tem certeza que deseja excluir o carro de placa <strong id="carroPlaca"></strong>?
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-danger" id="btnConfirmarExcluir">Excluir</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" />

    <script>
        let idCarroParaExcluir = 0;

        function confirmarExclusao(id, placa) {
            idCarroParaExcluir = id;
            $('#carroPlaca').text(placa);
            $('#modalExcluir').modal('show');
        }

        $('#btnConfirmarExcluir').click(function () {
            $.post('@Url.Action("DeleteAjax", "Carro")', { id: idCarroParaExcluir }, function (data) {
                if (data.sucesso) {
                    $('#modalExcluir').modal('hide');
                    location.reload();
                } else {
                    alert(data.mensagem || "Erro ao excluir.");
                }
            }).fail(function () {
                alert("Erro ao se comunicar com o servidor.");
            });
        });

        $(document).ready(function () {
            $('#tabelaCarros').DataTable({
                language: {
                    "search": "Buscar:",
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ carros",
                    "paginate": {
                        "first": "Primeiro",
                        "last": "Último",
                        "next": "Próximo",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
}